
;---------------------------------------------------------------------------
;  config.inc - OpenPRS config access
;
;  Created: Fri Sep 05 13:34:37 2014
;  Copyright  2014  Tim Niemueller [www.niemueller.de]
;  Licensed under GPLv2+ license, cf. LICENSE file
;---------------------------------------------------------------------------

declare cwp confval

load external "mod_config" "init"
load opf "config.opf"
