#*****************************************************************************
#      Makefile Build System for Fawkes: Plugin REST API Plugin
#                            -------------------
#   Created on Tue Apr 10 17:10:28 2018
#   Copyright (C) 2006-2018 by Tim Niemueller
#
#*****************************************************************************
#
#   This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation; either version 2 of the License, or
#   (at your option) any later version.
#
#*****************************************************************************

BASEDIR = ../../../..
include $(BASEDIR)/etc/buildsys/config.mk
include $(BUILDSYSDIR)/rest-api.mk

include $(BUILDSYSDIR)/base.mk
