#*****************************************************************************
#             Makefile Build System for Fawkes : RefBox Repeater
#                            -------------------
#   Created on Wed Apr 09 09:44:15 2008
#   Copyright (C) 2006-2008 by Tim Niemueller, AllemaniACs RoboCup Team
#
#   $Id$
#
#*****************************************************************************
#
#   This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation; either version 2 of the License, or
#   (at your option) any later version.
#
#*****************************************************************************

BASEDIR = ../../..

LIBS_refboxrep = fawkescore fawkesutils fawkesconfig fawkesnetcomm
OBJS_refboxrep = main.o refbox_state_sender.o midsize.o

OBJS_all =	$(OBJS_refboxrep)
BINS_all =	$(BINDIR)/refboxrep

include $(BASEDIR)/etc/buildsys/base.mk

