#*****************************************************************************
#            Makefile Build System for Fawkes : Plugin Tool
#                            -------------------
#   Created on Wed Nov 22 00:29:31 2006
#   Copyright (C) 2006-2008 by Tim Niemueller, AllemaniACs RoboCup Team
#
#*****************************************************************************
#
#   This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation; either version 2 of the License, or
#   (at your option) any later version.
#
#*****************************************************************************

BASEDIR = ../../..

LIBS_plugin = fawkescore fawkesutils fawkesnetcomm fawkesmainappmsgs
OBJS_plugin = main.o	\
	      plugin_tool.o

OBJS_all =	$(OBJS_plugin)
BINS_all =	$(BINDIR)/plugin

include $(BASEDIR)/etc/buildsys/base.mk

