
(defrule goal-expander-create-sequence
	?g <- (goal (mode SELECTED) (id TESTGOAL))
	=>
	(assert
		(plan (id TESTGOAL-PLAN) (goal-id TESTGOAL))
		(plan-action (id 1) (goal-id TESTGOAL) (plan-id TESTGOAL-PLAN)
                 (duration 4.0)
		             (action-name say-hello)
		             (param-names name) (param-values peggy))
		(plan-action (id 2) (goal-id TESTGOAL) (plan-id TESTGOAL-PLAN)
		             (duration 4.0)
		             (action-name print)
								 (param-names severity text)
		             (param-values warn "This is a print test"))
		(plan-action (id 3) (goal-id TESTGOAL) (plan-id TESTGOAL-PLAN)
		             (duration 4.0)
		             (action-name say-goodbye) (param-values peggy))
		(plan-action (id 4) (goal-id TESTGOAL) (plan-id TESTGOAL-PLAN)
		             (duration 4.0)
		             (action-name say-hello-again)
		             (param-names name) (param-values peggy))
		(plan-action (id 5) (goal-id TESTGOAL) (plan-id TESTGOAL-PLAN)
		             (duration 4.0)
		             (action-name say-cleanup))
	)
	(modify ?g (mode EXPANDED))
)
