
(defrule goal-expander-create-sequence
	?g <- (goal (mode SELECTED) (id ?goal-id) (class TESTGOAL))
	=>
	(bind ?plan-id (sym-cat ?goal-id -PLAN))
	(assert
		(plan (id ?plan-id) (goal-id ?goal-id))
		(plan-action (id 1) (goal-id ?goal-id) (plan-id ?plan-id)
                 (duration 4.0)
		             (action-name say-hello)
		             (param-names name) (param-values peggy))
		(plan-action (id 2) (goal-id ?goal-id) (plan-id ?plan-id)
		             (duration 4.0)
		             (action-name print)
								 (param-names severity text)
		             (param-values warn "This is a print test"))
		(plan-action (id 3) (goal-id ?goal-id) (plan-id ?plan-id)
		             (duration 4.0)
		             (action-name say-goodbye) (param-values peggy))
		(plan-action (id 4) (goal-id ?goal-id) (plan-id ?plan-id)
		             (duration 4.0)
		             (action-name say-hello-again)
		             (param-names name) (param-values peggy))
		(plan-action (id 5) (goal-id ?goal-id) (plan-id ?plan-id)
		             (duration 4.0)
		             (action-name say-cleanup))
	)
	(modify ?g (mode EXPANDED))
)
