#!/bin/bash

LIGHTTPD=`which lighttpd`

if [ -z "$LIGHTTPD" ]; then
	echo "lighttpd could not be found. Cannot start webview."
	exit 1
fi

if [ ! -e "../cfg/lighttpd/lighttpd.pem" ]; then
	echo "SSL certificate does not exist, creating."
	LOCALNAME=$(hostname -s).local
	echo "Creating certificate for hostname $LOCALNAME"
	COMMON_NAME=$LOCALNAME openssl req -new -x509 \
		-config ../cfg/lighttpd/openssl.conf \
		-keyout ../cfg/lighttpd/lighttpd.pem \
		-out ../cfg/lighttpd/lighttpd.pem \
		-days 3650 -nodes -batch
fi

$LIGHTTPD -f ../cfg/lighttpd/lighttpd.conf -D

