// Generated by the protocol buffer compiler.  DO NOT EDIT!

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "PuckDetectionResult.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace llsf_msgs {

namespace {

const ::google::protobuf::Descriptor* PuckDetectionResult_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  PuckDetectionResult_reflection_ = NULL;
const ::google::protobuf::EnumDescriptor* PuckDetectionResult_CompType_descriptor_ = NULL;

}  // namespace


void protobuf_AssignDesc_PuckDetectionResult_2eproto() {
  protobuf_AddDesc_PuckDetectionResult_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "PuckDetectionResult.proto");
  GOOGLE_CHECK(file != NULL);
  PuckDetectionResult_descriptor_ = file->message_type(0);
  static const int PuckDetectionResult_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PuckDetectionResult, positions_),
  };
  PuckDetectionResult_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      PuckDetectionResult_descriptor_,
      PuckDetectionResult::default_instance_,
      PuckDetectionResult_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PuckDetectionResult, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PuckDetectionResult, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(PuckDetectionResult));
  PuckDetectionResult_CompType_descriptor_ = PuckDetectionResult_descriptor_->enum_type(0);
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_PuckDetectionResult_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    PuckDetectionResult_descriptor_, &PuckDetectionResult::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_PuckDetectionResult_2eproto() {
  delete PuckDetectionResult::default_instance_;
  delete PuckDetectionResult_reflection_;
}

void protobuf_AddDesc_PuckDetectionResult_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::llsf_msgs::protobuf_AddDesc_Pose2D_2eproto();
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\031PuckDetectionResult.proto\022\tllsf_msgs\032\014"
    "Pose2D.proto\"d\n\023PuckDetectionResult\022$\n\tp"
    "ositions\030\001 \003(\0132\021.llsf_msgs.Pose2D\"\'\n\010Com"
    "pType\022\014\n\007COMP_ID\020\320\017\022\r\n\010MSG_TYPE\020\255\002", 154);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "PuckDetectionResult.proto", &protobuf_RegisterTypes);
  PuckDetectionResult::default_instance_ = new PuckDetectionResult();
  PuckDetectionResult::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_PuckDetectionResult_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_PuckDetectionResult_2eproto {
  StaticDescriptorInitializer_PuckDetectionResult_2eproto() {
    protobuf_AddDesc_PuckDetectionResult_2eproto();
  }
} static_descriptor_initializer_PuckDetectionResult_2eproto_;


// ===================================================================

const ::google::protobuf::EnumDescriptor* PuckDetectionResult_CompType_descriptor() {
  protobuf_AssignDescriptorsOnce();
  return PuckDetectionResult_CompType_descriptor_;
}
bool PuckDetectionResult_CompType_IsValid(int value) {
  switch(value) {
    case 301:
    case 2000:
      return true;
    default:
      return false;
  }
}

#ifndef _MSC_VER
const PuckDetectionResult_CompType PuckDetectionResult::COMP_ID;
const PuckDetectionResult_CompType PuckDetectionResult::MSG_TYPE;
const PuckDetectionResult_CompType PuckDetectionResult::CompType_MIN;
const PuckDetectionResult_CompType PuckDetectionResult::CompType_MAX;
const int PuckDetectionResult::CompType_ARRAYSIZE;
#endif  // _MSC_VER
#ifndef _MSC_VER
const int PuckDetectionResult::kPositionsFieldNumber;
#endif  // !_MSC_VER

PuckDetectionResult::PuckDetectionResult()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void PuckDetectionResult::InitAsDefaultInstance() {
}

PuckDetectionResult::PuckDetectionResult(const PuckDetectionResult& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void PuckDetectionResult::SharedCtor() {
  _cached_size_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

PuckDetectionResult::~PuckDetectionResult() {
  SharedDtor();
}

void PuckDetectionResult::SharedDtor() {
  if (this != default_instance_) {
  }
}

void PuckDetectionResult::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* PuckDetectionResult::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return PuckDetectionResult_descriptor_;
}

const PuckDetectionResult& PuckDetectionResult::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_PuckDetectionResult_2eproto();  return *default_instance_;
}

PuckDetectionResult* PuckDetectionResult::default_instance_ = NULL;

PuckDetectionResult* PuckDetectionResult::New() const {
  return new PuckDetectionResult;
}

void PuckDetectionResult::Clear() {
  positions_.Clear();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool PuckDetectionResult::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated .llsf_msgs.Pose2D positions = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_positions:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
                input, add_positions()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(10)) goto parse_positions;
        if (input->ExpectAtEnd()) return true;
        break;
      }
      
      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void PuckDetectionResult::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // repeated .llsf_msgs.Pose2D positions = 1;
  for (int i = 0; i < this->positions_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, this->positions(i), output);
  }
  
  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* PuckDetectionResult::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // repeated .llsf_msgs.Pose2D positions = 1;
  for (int i = 0; i < this->positions_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        1, this->positions(i), target);
  }
  
  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int PuckDetectionResult::ByteSize() const {
  int total_size = 0;
  
  // repeated .llsf_msgs.Pose2D positions = 1;
  total_size += 1 * this->positions_size();
  for (int i = 0; i < this->positions_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->positions(i));
  }
  
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void PuckDetectionResult::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const PuckDetectionResult* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const PuckDetectionResult*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void PuckDetectionResult::MergeFrom(const PuckDetectionResult& from) {
  GOOGLE_CHECK_NE(&from, this);
  positions_.MergeFrom(from.positions_);
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void PuckDetectionResult::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void PuckDetectionResult::CopyFrom(const PuckDetectionResult& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool PuckDetectionResult::IsInitialized() const {
  
  for (int i = 0; i < positions_size(); i++) {
    if (!this->positions(i).IsInitialized()) return false;
  }
  return true;
}

void PuckDetectionResult::Swap(PuckDetectionResult* other) {
  if (other != this) {
    positions_.Swap(&other->positions_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata PuckDetectionResult::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = PuckDetectionResult_descriptor_;
  metadata.reflection = PuckDetectionResult_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace llsf_msgs

// @@protoc_insertion_point(global_scope)
