
;---------------------------------------------------------------------------
;  example.inc - OpenPRS example agent
;
;  Created: Tue Sep 09 11:55:36 2014
;  Copyright  2014  Tim Niemueller [www.niemueller.de]
;  Licensed under GPLv2+ license, cf. LICENSE file
;---------------------------------------------------------------------------

; declare and load agent-specific elements
declare op_predicate  say

load opf "example.opf"
