
;---------------------------------------------------------------------------
;  meta-coalesce.inc - OpenPRS coalescinc meta OP include file
;
;  Created: Mon Sep 01 13:52:12 2014
;  Copyright  2014  Tim Niemueller [www.niemueller.de]
;  Licensed under GPLv2+ license, cf. LICENSE file
;---------------------------------------------------------------------------

load external "mod_utils" "init"
include "meta-coalesce.sym"
load opf "meta-coalesce.opf"
