#!/usr/bin/env bash

############################################################################
#  Annotation script, to be run after builds
#
#  Created: Tue Jan 22 11:42:58 2019 +0100
#  Copyright  2018-2019  Tim Niemueller [www.niemueller.org]
############################################################################

#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Library General Public License for more details.
#
#  Read the full text in the LICENSE.GPL file in the doc directory.

SCRIPT_PATH=$(dirname $(readlink -f ${BASH_SOURCE[0]}))

# Source standard environment, may setup ccache if available
source /etc/profile

source $SCRIPT_PATH/functions.sh

# Error out on any error in the script, pipes etc.
set -euo pipefail

for f in $SCRIPT_PATH/annotations.d/*.sh; do
	short_name=$(basename $f)
	short_name=${short_name%*.sh}
	if [ -n "${DEBUG:-}" ]; then
		$f
	else
		$f | buildkite-agent annotate --context "$short_name" --style info --append
	fi
done
