#!/bin/bash

############################################################################
#  Build script, will (usually) be executed in Docker container
#
#  Created: Wed Sep 26 14:19:27 2018 +0200
#  Copyright  2018  Tim Niemueller [www.niemueller.org]
############################################################################

#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Library General Public License for more details.
#
#  Read the full text in the LICENSE.GPL file in the doc directory.


# Source standard environment, may setup ccache if available
source /etc/profile

# Error out on any error in the script, pipes etc.
set -euo pipefail

# Ensure no old build artifacts remain
make -j$(nproc) clean
rm -rf bin/ lib/ plugins/

# Build software
make -j$(nproc) all gui

