#!/bin/bash

############################################################################
#  Webview frontend build script, will be executed in Docker container
#
#  Created: Thu Oct 11 21:59:26 2018 +0200
#  Copyright  2018  Tim Niemueller [www.niemueller.org]
############################################################################

#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Library General Public License for more details.
#
#  Read the full text in the LICENSE.GPL file in the doc directory.


# Source standard environment, may setup ccache if available
source /etc/profile

# Error out on any error in the script, pipes etc.
set -euo pipefail

# Get Angular CLI
echo 'prefix = ~/.npm' > ~/.npmrc
npm install --global @angular/cli
export PATH=$PATH:$HOME/.npm/bin

# Build webview frontend (also calls npm install)
cd src/plugins/webview/frontend
make NG_BUILD_FLAGS=""
