# Fawkes Buildkite Pipeline
# SPDX-License-Identifier: GPL-2.0-or-later

merged-pr-plugin: &merged-pr-plugin
  seek-oss/github-merged-pr#v1.1.2:
    mode: checkout

podman-plugin-base: &podman-plugin-base
  image: quay.io/fawkesrobotics/fawkes-builder:f40-ros2
  always-pull: true
  debug: true
  privileged: true
  environment: ["BUILDKITE", "BUILDKITE_LABEL"]

steps:
  - label: ":memo: pre-commit-checks"
    commands:
      - pre-commit run --all-files --hook-stage manual
    plugins:
      - *merged-pr-plugin
      - compono/podman#main:
          <<: *podman-plugin-base
          environment:
            - PRE_COMMIT_HOME=/var/cache/ccache/.pre-commit
          volumes:
            - "/var/lib/buildkite-agent/ccache_fedora:/var/cache/ccache:z"

  - wait

  - label: ":fedora: test"
    artifact_paths:
      - tests.out.d/**/*
    timeout_in_minutes: 20
    plugins:
      - *merged-pr-plugin
      - docker-compose#v4.12.0:
          run: fawkes
          config: docker-compose.yml
          env:
            - BUILDKITE_BUILD_NUMBER
          command:
            - .buildkite/test
            - .buildkite/annotate
          <<: *podman-plugin-base
          volumes:
            - /var/lib/buildkite-agent/ccache_fedora:/var/cache/ccache
