# Fawkes Buildkite Pipeline
# SPDX-License-Identifier: GPL-2.0-or-later

merged-pr-plugin: &merged-pr-plugin
  seek-oss/github-merged-pr#v1.0.1:
    mode: checkout

docker-plugin-base: &docker-plugin-base
  image: fawkesrobotics/fawkes-builder:fedora29-kinetic
  always-pull: true
  debug: true
  workdir: /workdir
  volumes: [".:/workdir"]
  environment: ["BUILDKITE"]

steps:
  - label: ":memo: Linter"
    command: .buildkite/lint
    plugins:
      <<: *merged-pr-plugin
      docker#v2.2.0:
        <<: *docker-plugin-base
        environment:
          - BUILDKITE
          - BUILDKITE_REPO
          - BUILDKITE_BRANCH
          - BUILDKITE_BUILD_CREATOR
          - BUILDKITE_BUILD_CREATOR_EMAIL
          # the following is set by the agent environment (ansible)
          - SSH_DEPLOY_PRIVKEY_COMMITTERS

  - wait

  - label: ":fedora: Fedora"
    command:
      - .buildkite/build
      - .buildkite/annotate
    plugins:
      <<: *merged-pr-plugin
      docker#v2.2.0:
        <<: *docker-plugin-base
        volumes:
          - .:/workdir
          - /var/lib/buildkite-agent/ccache_fedora:/var/cache/ccache

  - label: ":ubuntu: Ubuntu"
    command:
      - .buildkite/build
      - .buildkite/annotate
    plugins:
      <<: *merged-pr-plugin
      docker#v2.2.0:
        <<: *docker-plugin-base
        image: fawkesrobotics/fawkes-builder:ubuntu1804-melodic
        volumes:
          - .:/workdir
          - /var/lib/buildkite-agent/ccache_ubuntu:/var/cache/ccache

