# Fawkes Buildkite Pipeline
# SPDX-License-Identifier: GPL-2.0-or-later

merged-pr-plugin: &merged-pr-plugin
  seek-oss/github-merged-pr#v1.1.2:
    mode: checkout

podman-plugin-base: &podman-plugin-base
  image: quay.io/fawkesrobotics/fawkes-builder:f37
  always-pull: true
  debug: true
  privileged: true
  environment: ["BUILDKITE", "BUILDKITE_LABEL"]

steps:
  - label: ":memo: Linter"
    command: .buildkite/lint
    plugins:
      - *merged-pr-plugin
      - compono/podman#main:
          <<: *podman-plugin-base
          environment:
            - BUILDKITE
            - BUILDKITE_REPO
            - BUILDKITE_BRANCH
            - BUILDKITE_COMMIT
            - BUILDKITE_LABEL
            - BUILDKITE_BUILD_CREATOR
            - BUILDKITE_BUILD_CREATOR_EMAIL
            # the following is set by the agent environment (ansible)
            - SSH_DEPLOY_PRIVKEY_COMMITTERS

  - wait

  - label: ":fedora: test"
    artifact_paths:
      - tests.out.d/**/*
    timeout_in_minutes: 20
    plugins:
      - *merged-pr-plugin
      - docker-compose#v4.12.0:
          run: fawkes
          config: docker-compose.yml
          env:
            - BUILDKITE_BUILD_NUMBER
          command:
            - .buildkite/test
            - .buildkite/annotate
          <<: *podman-plugin-base
          volumes:
            - /var/lib/buildkite-agent/ccache_fedora:/var/cache/ccache
