#!/bin/bash

############################################################################
#  Script to run all tests
#
#  Created: Tue Oct 30 22:28:42 2018 -0700
#  Copyright  2018  Till Hofmann
############################################################################

#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Library General Public License for more details.
#
#  Read the full text in the LICENSE.GPL file in the doc directory.

# Source standard environment, may setup ccache if available
source /etc/profile

# Error out on any error in the script, pipes etc.
set -euo pipefail

# Run tests
make test

# Add more tests here if they don't run with make test
