#*****************************************************************************
#              Makefile Build System for Fawkes: Example Plugins
#                            -------------------
#   Created on Mon Feb 04 15:56:07 2008
#   Copyright (C) 2006-2008 by Tim Niemueller, AllemaniACs RoboCup Team
#
#*****************************************************************************
#
#   This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation; either version 2 of the License, or
#   (at your option) any later version.
#
#*****************************************************************************

BASEDIR = ../../..
include $(BASEDIR)/etc/buildsys/config.mk

SUBDIRS = basics ballposlog

include $(BUILDSYSDIR)/rules.mk

