#*****************************************************************************
#              Makefile Build System for Fawkes: WorldInfo Utilitiy Library
#                            -------------------
#   Created on Mon April 14 23:04:38 2008
#   copyright (C) 2008 by Daniel Beck, AllemaniACs RoboCup Team
#
#   $Id$
#
#*****************************************************************************
#
#   This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation; either version 2 of the License, or
#   (at your option) any later version.
#
#*****************************************************************************

BASEDIR = ../../..

LIBS_libworldinfo_utils = stdc++ netcomm geometry utils
OBJS_libworldinfo_utils = data_container.o

OBJS_all = $(OBJS_libworldinfo_utils)
LIBS_all = $(LIBDIR)/libworldinfo_utils.so

include $(BASEDIR)/etc/buildsys/base.mk
