#*****************************************************************************
#            Makefile Build System for Fawkes : Plugin Tool
#                            -------------------
#   Created on Wed Nov 22 00:29:31 2006
#   copyright (C) 2006 by Tim Niemueller, AllemaniACs RoboCup Team
#
#*****************************************************************************
#
#   This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation; either version 2 of the License, or
#   (at your option) any later version.
#
#*****************************************************************************
#
#           $Id$
# last modified: $Date$
#            by: $Author$
#

BASEDIR = ../../..

CFLAGS = -g

LIBS_config = core utils config netcomm
OBJS_config = main.o

OBJS_all =	$(OBJS_config)
BINS_all =	$(BINDIR)/config

include $(BASEDIR)/etc/buildsys/base.mk

