#*****************************************************************************
#               Makefile Build System for Fawkes: Config QA
#                            -------------------
#   Created on Thu Jan 11 15:38:35 2007
#   copyright (C) 2006-2007 by Tim Niemueller, AllemaniACs RoboCup Team
#
#*****************************************************************************
#
#   This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation; either version 2 of the License, or
#   (at your option) any later version.
#
#*****************************************************************************
#
#           $Id$
# last modified: $Date$
#            by: $Author$
#
#*****************************************************************************

BASEDIR = ../../../..

CFLAGS = -g

OBJS_qa_config = qa_config.o
LIBS_qa_config = config

BINS_all = $(BINDIR)/qa_config

include $(BASEDIR)/etc/buildsys/base.mk

