#*****************************************************************************
#            Makefile Build System for Fawkes: Nao Tools
#                            -------------------
#   Created on Fri Jun 17 13:57:02 2011
#   Copyright (C) 2006-2011 by Tim Niemueller, AllemaniACs RoboCup Team
#
#*****************************************************************************
#
#   This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation; either version 2 of the License, or
#   (at your option) any later version.
#
#*****************************************************************************

BASEDIR = ../../../..
include $(BASEDIR)/etc/buildsys/config.mk

SUBDIRS = naogui

include $(BUILDSYSDIR)/base.mk

