#*****************************************************************************
#         Makefile Build System for Fawkes : Laser Hough Transform QA
#                            -------------------
#   Created on Wed Dec 30 12:00:00 2009
#   Copyright (C) 2006-2009 by Tim Niemueller, AllemaniACs RoboCup Team
#
#*****************************************************************************
#
#   This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation; either version 2 of the License, or
#   (at your option) any later version.
#
#*****************************************************************************

BASEDIR = ../../../..

OBJS_qa_lineht := qa_lineht.o ../hough_transform.o
LIBS_qa_lineht := fawkescore fawkesutils

OBJS_all = $(OBJS_qa_lineht)
BINS_all = $(BINDIR)/qa_lineht

include $(BUILDSYSDIR)/base.mk
