#*****************************************************************************
#            Makefile Build System for Fawkes : Log Tool
#                            -------------------
#   Created on Sat Dec 15 02:02:54 2007
#   Copyright (C) 2006-2007 by Tim Niemueller, AllemaniACs RoboCup Team
#
#   $Id$
#
#*****************************************************************************
#
#   This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation; either version 2 of the License, or
#   (at your option) any later version.
#
#*****************************************************************************

BASEDIR = ../../..

LIBS_logview = core utils netcomm
OBJS_logview = main.o

OBJS_all =	$(OBJS_logview)
BINS_all =	$(BINDIR)/logview

include $(BASEDIR)/etc/buildsys/base.mk

