#*****************************************************************************
#            Makefile Build System for Fawkes : Log Tool
#                            -------------------
#   Created on Sat Dec 15 02:02:54 2007
#   Copyright (C) 2006-2008 by Tim Niemueller, AllemaniACs RoboCup Team
#
#*****************************************************************************
#
#   This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation; either version 2 of the License, or
#   (at your option) any later version.
#
#*****************************************************************************

BASEDIR = ../../..

LIBS_fflogview = fawkescore fawkesutils fawkesnetcomm
OBJS_fflogview = main.o

OBJS_all =	$(OBJS_fflogview)
BINS_all =	$(BINDIR)/fflogview

include $(BASEDIR)/etc/buildsys/base.mk

