#*****************************************************************************
#             Makefile Build System for Fawkes : Fawkes Info Tool
#                            -------------------
#   Created on Fri Aug 07 23:36:59 2009
#   Copyright (C) 2006-2010 by Tim Niemueller, AllemaniACs RoboCup Team
#
#*****************************************************************************
#
#   This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation; either version 2 of the License, or
#   (at your option) any later version.
#
#*****************************************************************************

BASEDIR = ../../..

include $(BASEDIR)/etc/buildsys/config.mk

LIBS_ffinfo = stdc++ fawkescore
OBJS_ffinfo = ffinfo.o

OBJS_all     =	$(OBJS_ffinfo)
BINS_all     =	$(BINDIR)/ffinfo
MANPAGES_all =	$(MANDIR)/man1/ffinfo.1

include $(BUILDSYSDIR)/base.mk
