#*****************************************************************************
#          akefile Build System for Fawkes: BBLogger Plugin QA
#                            -------------------
#   Created on Thu Nov 26 12:36:45 2009
#   Copyright (C) 2006-2009 by Tim Niemueller, AllemaniACs RoboCup Team
#
#*****************************************************************************
#
#   This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation; either version 2 of the License, or
#   (at your option) any later version.
#
#*****************************************************************************

BASEDIR = ../../../..
include $(BASEDIR)/etc/buildsys/config.mk

LIBS_qa_bblogger_produce = fawkescore fawkesutils fawkesblackboard TestInterface
OBJS_qa_bblogger_produce = qa_bblogger_produce.o
BINS_all = $(BINDIR)/qa_bblogger_produce

OBJS_all = $(OBJS_qa_bblogger_produce)

include $(BUILDSYSDIR)/base.mk
