function(depend_on_clipsmm target)
  depend_on_pkgconfig_libs(${target} clipsmm-1.0)
  target_compile_options(${target} PUBLIC -DHAVE_CLIPS ${CLIPSMM_CFLAGS})
  target_link_libraries(${target} ${CLIPSMM_LDFLAGS})
  target_compile_features(${target} PUBLIC cxx_std_14)
endfunction()
