pkg_check_modules(urdfdom_headers_4 urdfdom_headers>=0.40)
remember_dependency(urdfdom_headers_4)
if(urdfdom_headers_4_FOUND)
  set(HAVE_URDFDOM_TYPES_H 1)
endif()

function(depend_on_kdl_parser target)
  optional_depend_on_pkgconfig_libs(${target} urdfdom_headers_4
                                    urdfdom_headers_4_deps_found)
  if(urdfdom_headers_4_deps_found)
    target_compile_options(${target} PUBLIC -DHAVE_URDFDOM_TYPES_H)
  else()
    depend_on_pkgconfig_libs(${target} urdfdom_headers)
  endif()
  optional_depend_on_pkgconfig_libs(${target} orocos-kdl orocos-kdl_deps_found)
  if(NOT orocos-kdl_deps_found)
    depend_on_pkgconfig_libs(${target} orocos_kdl)
  endif()
  depend_on_pkgconfig_libs(${target} "urdfdom;tinyxml")
endfunction()
