pkg_check_modules(libcrypto libcrypto)
pkg_check_modules(openssl openssl)

if(libcrypto_FOUND OR openssl_FOUND)
  set(ENCRYPTION_SUPPORT 1)
endif()
function(depend_on_libcrypto target)
  if(${libcrypto_FOUND} OR ${openssl_FOUND})
    target_compile_options(${target} PRIVATE -DHAVE_LIBCRYPTO)
    if(${libcrypto_FOUND})
      target_compile_options(${target} PRIVATE ${libcyrpto_CFLAGS})
      target_link_libraries(${target} ${libcrypto_LDFLAGS})
    else()
      target_compile_options(${target} PRIVATE ${openssl_CFLAGS})
      target_link_libraries(${target} ${openssl_LDFLAGS})
    endif()
  else()
    message(WARNING "Omitting encryption support (OpenSSL/libcrypto not found)")
  endif()
endfunction()
