function(depend_on_libcrypto target)
  optional_depend_on_pkgconfig_libs(${target} libcrypto libcrypto_dep_found)
  if(libcrypto_dep_found)
    target_compile_definitions(${target} PRIVATE HAVE_LIBCRYPTO)
  else()
    optional_depend_on_pkgconfig_libs(${target} openssl openssl_dep_found)
    if(NOT openssl_dep_found)
      build_skipped_message(${target} "encryption support (OpenSSL/libcrypto)")
    endif()
  endif()
endfunction()
