find_package(Protobuf)

function(depend_on_protobuf target)
  if(Protobuf_FOUND)
    target_link_libraries(${target} ${Protobuf_LIBRARIES})
    target_include_directories(${target} PUBLIC ${Protobuf_INCLUDE_DIRS})
  else()
    disable_target({target})
    build_skipped_message(${target} "Protobuf")
  endif()
endfunction()

function(depend_on_protobuf_comm target)
  depend_on_pkgconfig_libs(${target} protobuf_comm)
endfunction()
