set(yamlcpp_deps "yaml-cpp")
function(depend_on_yamlcpp target)
  target_compile_options(${target} PUBLIC -DHAVE_YAMLCPP ${yaml-cpp_CFLAGS})
  target_link_libraries(${target} ${yaml-cpp_LDFLAGS})
  target_compile_options(${target} PUBLIC -DHAVE_YAMLCPP_NODE_MARK)
endfunction()
