#*****************************************************************************
#                   Makefile Build System for Fawkes: Tools
#                            -------------------
#   Created on Tue Nov 21 18:36:28 2006
#   Copyright (C) 2006-2009 by Tim Niemueller, AllemaniACs RoboCup Team
#
#*****************************************************************************
#
#   This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation; either version 2 of the License, or
#   (at your option) any later version.
#
#*****************************************************************************

BASEDIR = ../..

SUBDIRS = plugin logview config plugin_gui netloggui \
	  lasergui skillgui battery_monitor ffinfo vision set_pose \
		eclipse_debugger plugin_generator pddl_parser laser_calibration

include $(BASEDIR)/etc/buildsys/config.mk
include $(BUILDSYSDIR)/rules.mk

