#*****************************************************************************
#                   Makefile Build System for Fawkes: tools
#                            -------------------
#   Created on Tue Nov 21 18:36:28 2006
#   copyright (C) 2006 by Tim Niemueller, AllemaniACs RoboCup Team
#
#*****************************************************************************
#
#   This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation; either version 2 of the License, or
#   (at your option) any later version.
#
#*****************************************************************************

BASEDIR = ../..

SUBDIRS = blackboard plugin logview config plugin_gui \
	  netlog_monitor refboxrep worldinfo_viewer \
	  config_editor

include $(BASEDIR)/etc/buildsys/config.mk
include $(BASEDIR)/etc/buildsys/rules.mk

